type="webpack"
account_id="YOUR_ACCOUNT_NUMBER"
zone_id="YOUR_ZONE_ID"
route=""
usage_model=""
compatibility_flags=[]
workers_dev=false
site={bucket="./dist", entry-point="workers-site"}
compatibility_date="2021-10-22"

[env.stage]
name="stage_pelefele_com"
route="stage.pelefele.com/*"
workers_dev=false

[env.prod]
name="prod_pelefele_com"
route="pelefele.com/*"
workers_dev=false
